### PR TITLE
running Sauce tests with IE11

### PR DESCRIPTION
**Pull request by dlockhart**

### CODE REVIEW

**Comment by dlockhart** [comment]
Needed to include the `fetch` polyfill for IE11, which is probably why it was being excluded from Sauce. :)

**Comment by CodeBaboon** [comment]
Probably needs a promise polyfill as well?

**Comment by dlockhart** [comment]
Yup, working on that now. It's not as obvious... still failing weirdly even with the promise polyfill.

**Comment by dlockhart** [comment]
OK hopefully have it sorted. There were a few things going on that were breaking IE11:
1. Missing fetch polyfill
2. Missing promise polyfill
3. The way IE11 dealt with the URL, it was getting a mismatch between `http://example.com` (no trailing slash) and `http://example.com/` (trailing slash). So that meant the stub `withArgs` wasn't getting a hit and wasn't returning anything.
4. Lastly, the check for `expect(component._removeBannerUrl)` was failing because in IE11 only `_removeBannerUrl` was `null`. This was because `_onFetchError` was getting called that blanks it out, which was caused by the `organizationUrl` initially being `undefined` (the fixture gets attached but no attribute is set yet) and so it goes ahead and makes a request for an `undefined` URL. This happened in all browsers, but I think because of a timing issue in IE11 the value was getting nulled out at just the right time.

Good times!

**Pull request merged**
