### PR TITLE
Some initial setup

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Still need to do the CI stuff

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
image

**Comment by ryantmer** [comment]
@jstefaniuk-d2l you're just always pair programming, it seems. With yourself.

**Comment by jstefaniuk-d2l** [comment]
image

**Comment by jstefaniuk-d2l** [comment]
So do we need to push to the cdn for this? or is it good without the travis publishing stuff?

**Comment by ryantmer** [comment]
As is I believe it would fail anyway - the `CDN_SECRET` isn't set in .travis.yml. If it's still in early dev, though, you can just reference it via git in other projects' bower.json. Probably more conducive to rapid development for the first stages?

**Comment by jstefaniuk-d2l** [comment]
What I meant is, shall I set up the `CDN_SECRET`/etc as part of this PR?

**Comment by CodeBaboon** [comment]
We aren't going to get far without it. And it feels like scaffolding, which is the story. I vote with Shia - Do it.

**Comment by CodeBaboon** [comment]
But wait, won't this just bake into brightspace-integration?

**Comment by jstefaniuk-d2l** [comment]
https://github.com/Brightspace/brightspace-integration/pull/441 (here's a bsi PR for when this gets in, I tested it out quickly with bower link)

**Comment by jstefaniuk-d2l** [comment]
Ready for review I'd say

**Comment by cgalvind2l** [comment]
The only thing I think is missing is a demo. Thoughts on doing one of those?

**Comment by jstefaniuk-d2l** [comment]
Honestly, right now I'm just interested in getting our thing on the page so that everyone can get into the polymer stuff asap, but I'll look into doing a demo after that's done

**Comment by jstefaniuk-d2l** [comment]
Unless you or Dave feel that it's necessary right now, in which case let me know!

**Comment by CodeBaboon** [comment]
Yeah I thought of the demo when I reviewed but it seems like something we can add in as we go.

**Pull request merged**
